import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { fileURLToPath } from 'node:url';

import index from '../data/cwe/index.js';

const here = fileURLToPath(new URL('.', import.meta.url));
const rootDir = path.join(here, '..', 'data', 'cwe');

function walk(dir) {
	const out = [];
	for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
		const abs = path.join(dir, e.name);
		if (e.isDirectory()) out.push(...walk(abs));
		else if (e.name.endsWith('.js') && e.name !== 'index.js') out.push(abs);
	}
	return out;
}

test('cwe index covers every entry in every chunk, with no stale or duplicate ids', async () => {
	const seen = new Map(); // id -> spec
	let entries = 0;
	for (const abs of walk(rootDir)) {
		const spec = path.relative(rootDir, abs).split(path.sep).join('/');
		const mod = await import(pathToFileURL(abs).href);
		for (const e of mod.default || []) {
			entries++;
			assert.match(String(e.id), /^CWE-\d+$/, `${spec} malformed id ${e.id}`);
			const prev = seen.get(String(e.id));
			assert.equal(prev, undefined, `id ${e.id} duplicated in ${prev} and ${spec}`);
			seen.set(String(e.id), spec);
		}
	}

	assert.equal(entries, Object.keys(index).length,
		'index must have exactly one entry per handbook entry (regenerate with scripts/cwe-index.mjs)');
	for (const [key, spec] of Object.entries(index)) {
		assert.equal(seen.get(key), spec, `index maps ${key} to ${spec} but it lives in ${seen.get(key)}`);
	}
});

test('index is generated (sorted ascending), not hand-edited', () => {
	const src = fs.readFileSync(path.join(rootDir, 'index.js'), 'utf8');
	assert.match(src, /AUTO-GENERATED by scripts\/cwe-index\.mjs/, 'index.js looks hand-edited; regenerate it');
	assert.match(src, /^export default \{\n\t"CWE-5": "expansion\/gap-01\.js",\s*$/m, 'first (CWE-5) entry missing/moved');
});
