#!/usr/bin/env node
// Generates data/cwe/index.js — a tiny lazy-loading manifest that maps each CWE id to
// the chunk file (relative to data/cwe/) that owns it. This metadata file is imported
// eagerly by src/ui/cwe.js so a CWE can be looked up and a single chunk is `import()`-ed
// on demand instead of pulling all ~41 chunks / 900+ entries into the app at startup.
//
// Run: node scripts/cwe-index.mjs   (regenerates data/cwe/index.js)
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { fileURLToPath } from 'node:url';

const here = fileURLToPath(new URL('.', import.meta.url));
const rootDir = path.join(here, '..', 'data', 'cwe');

function walk(dir) {
	const out = [];
	for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
		const abs = path.join(dir, e.name);
		if (e.isDirectory()) out.push(...walk(abs));
		else if (e.name.endsWith('.js') && e.name !== 'index.js') out.push(abs);
	}
	return out;
}

const map = {};
let dupes = false;
for (const abs of walk(rootDir)) {
	const spec = path.relative(rootDir, abs).split(path.sep).join('/');
	const mod = await import(pathToFileURL(abs).href);
	for (const e of mod.default || []) {
		const key = String(e.id);
		if (map[key] && map[key] !== spec) {
			console.error(`cwe-index: CWE id ${key} lives in both ${map[key]} and ${spec}`);
			dupes = true;
		} else {
			map[key] = spec;
		}
	}
}
if (dupes) process.exit(1);

const ids = Object.keys(map).sort((a, b) => +a.replace(/\D/g, '') - +b.replace(/\D/g, ''));
const body = ids.map((id) => `\t${JSON.stringify(id)}: ${JSON.stringify(map[id])},`).join('\n');
const content = '// AUTO-GENERATED by scripts/cwe-index.mjs — do not edit by hand.\n'
	+ '// CWE id → chunk file (relative to data/cwe/) for lazy loading.\n'
	+ 'export default {\n' + body + '\n};\n';
fs.writeFileSync(path.join(rootDir, 'index.js'), content);
const n = ids.length;
const fileCount = walk(rootDir).length;
console.log(`cwe-index: ${n} ids → ${fileCount} chunks (wrote data/cwe/index.js)`);
